#!/bin/sh
set -e

gbp import-dsc --debian-branch=pk4 --upstream-branch=upstream "$1" "$2"
# Add local gbp.conf to override any branch settings in 'debian/gbp.conf'
# (since this checkout wasn't created by "gbp clone"). We want to be sure the
# branches exist so we can build the package right away.
cat <<EOF > "$2"/.git/gbp.conf
[DEFAULT]
upstream-branch = upstream
debian-branch = pk4
EOF
