---
stages:
  - check
  - package

python-lint:
  stage: check
  image: debian:sid
  before_script:
    - apt -y update
    - apt -y install ruff
  script:
    - ruff check .

salsaci:
  stage: package
  trigger:
    include: debian/salsa-ci.yml
    strategy: depend
