---
include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/6a40df92957c8ce9ee741aaccc5daaaf70545b1e/templates/ci-fairy.yml'

default:
  # Protect CI infra from rogue jobs
  timeout: 15 minutes
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  FDO_UPSTREAM_REPO: agx/git-buildpackage

stages:
  - check
  - package

python-lint:
  stage: check
  image: debian:sid
  before_script:
    - apt -y update
    - apt -y install ruff
  script:
    # Ruff is fast, run it twice to have junit and stout:
    - ruff check --output-format=junit --output-file=ruff-junit.xml . || true
    - ruff check .
  artifacts:
    paths:
      - ruff-junit.xml
    reports:
      junit: ruff-junit.xml

python-tests:
  stage: check
  image: debian:sid
  variables:
    PYTEST_ARGS: --junit-xml=pytest-junit.xml
  before_script:
    - apt -y update
    - apt -y build-dep .
  script:
    - git submodule update --init -- tests/component/deb/data/
    - python3 setup.py build
    - make syntax-check
    - make test
  artifacts:
    paths:
      - pytest-junit.xml
    reports:
      junit: pytest-junit.xml

python-typecheck:
  stage: check
  image: debian:sid
  variables:
    MYPY_ARGS: --junit-xml=mypy-junit.xml
  before_script:
    - apt -y update
    - apt -y build-dep .
    - apt -y install mypy
  script:
    - python3 setup.py build
    - make type-check
  artifacts:
    paths:
      - mypy-junit.xml
    reports:
      junit: mypy-junit.xml

# Sanity checks of MR settings and commit logs
sanity:
  extends:
    - .fdo.ci-fairy
  stage: check
  variables:
    GIT_DEPTH: "100"
  needs: []
  script: |
    ci-fairy check-commits --signed-off-by --junit-xml=commit-message-junit-report.xml
  artifacts:
    reports:
      junit: commit-message-junit-report.xml
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'

salsaci:
  stage: package
  trigger:
    include: debian/salsa-ci.yml
    strategy: depend
