---
stages:
  - check
  - package

python-lint:
  stage: check
  image: debian:sid
  before_script:
    - apt -y update
    - apt -y install ruff
  script:
    # Ruff is fast, run it twice to have junit and stout:
    - ruff check --output-format=junit --output-file=ruff-junit.xml . || true
    - ruff check .
  artifacts:
    paths:
      - ruff-junit.xml
    reports:
      junit: ruff-junit.xml

salsaci:
  stage: package
  trigger:
    include: debian/salsa-ci.yml
    strategy: depend
