#!/usr/bin/python
#
# run debuild in a git repository
#
# (c) 2006 Guido Guenther <agx@sigxcpu.org>
# License: GPLv2

import sys,os,commands,re
import optparse

build_cmd='debuild'
clean_cmd='%s clean' % build_cmd
    
def get_version():
    versionre=re.compile('^Version:\s+(?P<version>[\d\w~\-\.]+)$')
    (status, out) = commands.getstatusoutput('dpkg-parsechangelog')
    for line in out.split('\n'):
        m=versionre.match(line)
        if m:
            return m.group('version')

def exec_command(cmd):
    print "Running:", cmd
    ret=os.system(cmd)
    if ret:
        print >>sys.stderr,"%s failed" % cmd
        return False, ret
    else:
        return True, 0

def main(argv):
    args = [ arg for arg in argv[1:] if arg.find('--git-') == 0 ]
    dpkg_args = [ arg for arg in argv[1:] if arg.find('--git-') == -1 ]

    parser=optparse.OptionParser()
    parser.add_option("--git-ignore-new", action="store_true", dest="ignore_new", default=False,
                      help="build with incommited changes in the source tree")
    parser.add_option("--git-tag", action="store_true", dest="tag", default=False,
                      help="build with uncommited changes in the source tree")
    (options, args) = parser.parse_args(args)

    if not options.ignore_new:
        if not exec_command(clean_cmd)[0]: sys.exit(1)
        (status, out) = commands.getstatusoutput('git status')
        msgs=out.split('\n')
        if msgs[0] != 'nothing to commit':
            print "You have uncommitted changes in your source tree:"
            print out
            print "Use --git-ignore_new to ovverride"
            sys.exit(1)
    cmd=build_cmd+' -i.git '+" ".join(dpkg_args)
    if not exec_command(cmd)[0]: sys.exit(1)
    version=get_version()
    if version and options.tag:
        print "Tagging", version
        if not exec_command('git-tag %s' % version)[0]: sys.exit(1)
    else:
        print >>sys.stderr,"Can't parse version from changes file"

if __name__ == '__main__':
    sys.exit(main(sys.argv))

# vim:et:ts=4:sw=4:
