#!/bin/sh

set -e
set -x

git init .
git config user.email "you@example.com"
git config user.name "Doesnot Matter"
git add .
git commit -m"Smoketest" -a

gbp buildpackage-rpm --help

# Build an RPM of ourselfes if build-deps are available
if python3 -c "import setuptools"; then
  gbp buildpackage-rpm --git-packaging-dir=packaging/ \
                       -D'%__python3 /usr/bin/python3' \
                       -D'%__python /usr/bin/python3' \
                       -bb --nodeps
fi
