#!/bin/sh
#
# Tag, upload to the Debian archive and push to the remote

set -e

REMOTE=salsa+rw

if gbp config upload.remote; then
    REMOTE="$(gbp config upload.remote)"
fi

VERSION="$(dpkg-parsechangelog -S Version)"
SOURCE="$(dpkg-parsechangelog -S Source)"
CHANGES="../${SOURCE}_${VERSION}_source.changes"

less --quit-at-eof "${CHANGES}"
echo "Hit <RETURN> to upload, <CTRL>-C to quit"
read -r VAL

gbp tag
debsign -S

dput "${CHANGES}"
gbp push "${REMOTE}"
